# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  author: TACACS-RS Team
  description: Patroni-managed PostgreSQL HA cluster for policy-ingest service
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []

galaxy_tags:
  - postgresql
  - patroni
  - ha
  - database
