# SPDX-License-Identifier: AGPL-3.0-only
# tacacs_common - Default variables
---
# User and group
tacacs_user: tacacs
tacacs_group: tacacs
tacacs_home_dir: /var/lib/tacacs

# Directories
tacacs_config_dir: /etc/tacacs
tacacs_log_dir: /var/log/tacacs
tacacs_bin_dir: /usr/local/bin

# Network
tacacs_http_port: 8080

# Firewall
tacacs_configure_firewall: true

# Required packages (override per OS family)
tacacs_required_packages: []
