# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  author: TACACS-RS Team
  description: FRR-based BGP anycast for TACACS+ geographic distribution
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: tacacs_server

galaxy_tags:
  - bgp
  - anycast
  - frr
  - routing
  - ha
