# SPDX-License-Identifier: Apache-2.0
# pgbouncer - Handlers
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart pgbouncer
  ansible.builtin.systemd:
    name: pgbouncer
    state: restarted

- name: Reload pgbouncer
  ansible.builtin.systemd:
    name: pgbouncer
    state: reloaded
