# SPDX-License-Identifier: AGPL-3.0-only
---
galaxy_info:
  author: TACACS-RS Team
  description: Deploy and configure TACACS+ server
  license: AGPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: tacacs_common
