# SPDX-License-Identifier: Apache-2.0
# tacacs_server - Handlers
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart tacacs-server
  ansible.builtin.systemd:
    name: tacacs-server
    state: restarted

- name: Reload tacacs-server
  ansible.builtin.systemd:
    name: tacacs-server
    state: reloaded

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  when: ansible_os_family == "RedHat"
