[project]
site_name = "USG TACACS"
site_description = "Documentation for USG TACACS"
site_author = "John Edward Willman V <mailto:john.willman.1@us.af.mil>"
docs_dir = "docs"
site_dir = "site"
repo_url = "https://github.com/192d-Cyberspace-Control-Squadron/usg-tacacs"
repo_name = "192d-CYCS/usg-tacacs"


[project.theme]
variant = "modern"
font.text = "Lato"
language = "en"
logo = "images/logo.png"
features = ["search.highlight"]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.theme.palette]
scheme = "slate"

[project.extra]
generator = true

[project.extra.consent]
title = "Cookie consent"
description = """
    We use cookies to recognize your repeated visits and preferences, as well
    as to measure the effectiveness of our documentation and whether users
    find what they're searching for. With your consent, you're helping us to
    make our documentation better.
"""

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
pygments_lang_class = true
line_spans = "__span"

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.admonition]

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.attr_list]

[project.markdown_extensions.tables]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
